# Generated by Django 5.2.5 on 2025-08-22 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': '0. School Years',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '2. School',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée')], max_length=100)),
                ('name', models.CharField(choices=[('1ere Annee A', '1ère Année A'), ('1ere Annee B', '1ère Année B'), ('1ere Annee C', '1ère Année C'), ('2eme Annee A', '2ème Année A'), ('2eme Annee B', '2ème Année B'), ('2eme Annee C', '2ème Année C'), ('3eme Annee A', '3ème Année A'), ('3eme Annee B', '3ème Année B'), ('3eme Annee C', '3ème Année C'), ('4eme Annee A', '4ème Année A'), ('4eme Annee B', '4ème Année B'), ('4eme Annee C', '4ème Année C'), ('5eme Annee A', '5ème Année A'), ('5eme Annee B', '5ème Année B'), ('5eme Annee C', '5ème Année C'), ('6eme Annee A', '6ème Année A'), ('6eme Annee B', '6ème Année B'), ('6eme Annee C', '6ème Année C'), ('7eme Annee A', '7ème Année A'), ('7eme Annee B', '7ème Année B'), ('7eme Annee C', '7ème Année C'), ('8eme Annee A', '8ème Année A'), ('8eme Annee B', '8ème Année B'), ('8eme Annee C', '8ème Année C'), ('9eme Annee A', '9ème Année A'), ('9eme Annee B', '9ème Année B'), ('9eme Annee C', '9ème Année C'), ('10eme Annee A', '10ème Année A'), ('10eme Annee B', '10ème Année B'), ('10eme Annee C', '10ème Année C'), ('11eme S Litteraire 1', '11ème S Littéraire 1'), ('11eme S Litteraire 2', '11ème S Littéraire 2'), ('11eme S Litteraire 3', '11ème S Littéraire 3'), ('11eme S Scientifique 1', '11ème S Scientifique 1'), ('11eme S Scientifique 2', '11ème S Scientifique 2'), ('11eme S Scientifique 3', '11ème S Scientifique 3'), ('12eme S Litteraire 1', '12ème S Littéraire 1'), ('12eme S Litteraire 2', '12ème S Littéraire 2'), ('12eme S Litteraire 3', '12ème S Littéraire 3'), ('12eme S Scientifique 1', '12ème S Scientifique 1'), ('12eme S Scientifique 2', '12ème S Scientifique 2'), ('12eme S Scientifique 3', '12ème S Scientifique 3'), ('T SS 1', 'T SS 1'), ('T SS 2', 'T SS 2'), ('T SS 3', 'T SS 3'), ('T SE 1', 'T SE 1'), ('T SE 2', 'T SE 2'), ('T SE 3', 'T SE 3'), ('T SM 1', 'T SM 1'), ('T SM 2', 'T SM 2'), ('T SM 3', 'T SM 3')], max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.schoolyear')),
            ],
            options={
                'verbose_name_plural': '3. Classe',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=100, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='student_images/')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.classe')),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.schoolyear')),
            ],
            options={
                'verbose_name_plural': '4. Student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.classe')),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.schoolyear')),
            ],
            options={
                'verbose_name_plural': '5. Teacher',
            },
        ),
        migrations.CreateModel(
            name='StudentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence', models.IntegerField(default=0)),
                ('absence_autorisee', models.IntegerField(default=0)),
                ('presence', models.IntegerField(default=0)),
                ('mauvaise_conduite', models.IntegerField(default=0)),
                ('bonne_conduite', models.IntegerField(default=0)),
                ('participation_active', models.IntegerField(default=0)),
                ('participation_moyenne', models.IntegerField(default=0)),
                ('participation_faible', models.IntegerField(default=0)),
                ('bonne_moyenne', models.IntegerField(default=0)),
                ('mauvaise_moyenne', models.IntegerField(default=0)),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
            options={
                'verbose_name_plural': '8. Student Statistics',
                'unique_together': {('student', 'school_year')},
            },
        ),
    ]
